services:
  postgres-standby:
    image: postgres:${POSTGRES_VERSION} # MUST match the primary's major version
    container_name: postgres-standby
    restart: always
    # DO NOT set POSTGRES_USER/PASSWORD/DB here initially.
    # The data directory will be populated by pg_basebackup.
    # We only need the replication password for the backup script.
    environment:
      PRIMARY_HOST: ${PRIMARY_HOST} # IP Address of Server A
      REPLICATION_USER: ${REPLICATION_USER}
      REPLICATION_PASSWORD: ${REPLICATION_PASSWORD} # Same as on primary
      PGDATA: /var/lib/postgresql/data/pgdata # MUST match target dir in entrypoint
    volumes:
      - ./postgres/data:/var/lib/postgresql/data # Persist data
      - ./postgres/scripts:/docker-entrypoint-initdb.d # Use initdb.d for the custom script
    ports:
      - "5434:5432"
    # We override the default command to run our script first
    command: ["/docker-entrypoint-initdb.d/setup_standby.sh"]
  garage:
    image: dxflrs/garage:${GARAGE_VERSION}
    restart: unless-stopped
    volumes:
      - ./garage/garage.toml:/etc/garage.toml
      - ./garage/data:/var/lib/garage/data
      - ./garage/meta:/var/lib/garage/meta
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      GARAGE_RPC_SECRET: ${GARAGE_RPC_SECRET}
      GARAGE_ADMIN_TOKEN: ${GARAGE_ADMIN_TOKEN}
    command: server
