apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # Use the internal docker network hostname 'prometheus'
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: true
