global:
  scrape_interval: 60s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus itself

  - job_name: 'node-exporter'
    static_configs:
      # Use the internal docker network hostname 'node-exporter'
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      # Use the internal docker network hostname 'cadvisor' and its internal port 8080
      - targets: ['cadvisor:8080']

  - job_name: 'postgres-exporter'
    static_configs:
      # Use the internal docker network hostname 'postgres-exporter'
      - targets: ['postgres-exporter:9187']

  - job_name: 'garage'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['garage:3903']

  - job_name: 'stalwart'
    metrics_path: /metrics/prometheus
    scheme: http
    static_configs:
      - targets: ['stalwart-mail:8080']
    basic_auth:
      username: 'METRIC_USER'
      password: 'METRIC_PASSWORD'
